name: quantum_dots
description: the design system for wippy global product
version: 0.0.1
homepage: https://github.com/nrise/Quantum-Dots
topics:
  - animations
  - ui
  - design-system
  - design

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  foundation:
  button:
  input:
  toast:
  markdown_text:
  progress:
  spinner:
  header:
  common_widget:
  bottom_sheet:
  badge:
  chips:
  popup:
  empty_states:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
